export type ConundrumCategory =
  | '伦理·公平'
  | '科学·探索'
  | '逻辑·资源'
  | '创意·审美'
  | '节日·情境'
  | '元认知';

export interface Conundrum {
  id: string;
  title: string;
  original: string;
  category: ConundrumCategory;
  situation: string;
  question: string;
  discussion: string[];
  aiProject: string;
  bilibiliVideos?: { title: string; bvid: string; url: string }[];
  bilibiliSearch: string;
}

export const CONUNDRUM_CATEGORIES: ConundrumCategory[] = [
  '伦理·公平',
  '科学·探索',
  '逻辑·资源',
  '创意·审美',
  '节日·情境',
  '元认知',
];

export const CONUNDRA: Conundrum[] = [
  {
    id: 'conundrum-conundrum',
    title: '难题的难题',
    original: 'The Conundrum Conundrum',
    category: '元认知',
    situation: '最难的问题到处都是——它们往往没有现成答案。',
    question: '面对最难解决的问题，领导者最该具备什么品质？',
    discussion: [
      '勇气、智慧、共情、决断，哪个更重要？',
      '为什么这类问题没有标准答案？',
    ],
    aiProject: '做一个「我的领导力品质」测评小网页，孩子给自己打分并生成一张卡片。',
    bilibiliVideos: [{ title: '马斯克网校考题 #33', bvid: 'BV1Rar5YkEfR', url: 'https://www.bilibili.com/video/BV1Rar5YkEfR/' }],
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Conundrum%20Conundrum',
  },
  {
    id: 'arctic',
    title: '北极难题',
    original: 'The Arctic Conundrum',
    category: '科学·探索',
    situation: '北极科考与生态面临开发与保护的拉扯。',
    question: '怎么在利用北极和守护北极之间做权衡？',
    discussion: [
      '科学价值、原住民权益、环保，三方怎么排？',
      '短期收益与长期代价，谁说了算？',
    ],
    aiProject: '做一张「北极生态科普」互动页，点开看不同物种的处境。',
    bilibiliVideos: [{ title: 'The Arctic Conundrum', bvid: 'BV11HK46eE44', url: 'https://www.bilibili.com/video/BV11HK46eE44/' }, { title: '马斯克网校考题 #14', bvid: 'BV19qr5YuEAX', url: 'https://www.bilibili.com/video/BV19qr5YuEAX/' }],
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Arctic%20Conundrum',
  },
  {
    id: 'light',
    title: '灯光难题',
    original: 'The Light Conundrum',
    category: '科学·探索',
    situation: '城市太亮，影响了星空、昆虫和睡眠。',
    question: '怎样平衡安全照明与暗夜保护？',
    discussion: [
      '节能、安全、生态、美观，四者怎么排优先级？',
      '能不能用设计同时顾全几边？',
    ],
    aiProject: '做一个「暗夜地图」可视化，标出家里附近的光污染程度。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Light%20Conundrum',
    bilibiliVideos: [{ title: 'The Light Conundrum', bvid: 'BV1ver5Y3EGQ', url: 'https://www.bilibili.com/video/BV1ver5Y3EGQ/' }],
  },
  {
    id: 'ferry',
    title: '渡轮难题',
    original: 'The Ferry Conundrum',
    category: '逻辑·资源',
    situation: '两座城市被水隔开，急需更好的连接方式。',
    question: '城市规划者该怎么做——建桥、挖隧道、留渡轮，还是不建？',
    discussion: [
      '成本、环保、便利、风险，如何权衡？',
      '不同人群诉求冲突时，听谁的？',
    ],
    aiProject: '做「交通方案对比」小工具，孩子输入条件，AI 给出三种方案利弊。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Ferry%20Conundrum',
    bilibiliVideos: [{ title: 'The Ferry Conundrum', bvid: 'BV1ver5Y3EKs', url: 'https://www.bilibili.com/video/BV1ver5Y3EKs/' }],
  },
  {
    id: 'island',
    title: '小岛难题',
    original: 'The Island Conundrum',
    category: '逻辑·资源',
    situation: '一座孤岛社区要决定自己的资源怎么用。',
    question: '岛上资源怎么分配、规则由谁定？',
    discussion: [
      '自治与公平、可持续与当下需求，矛盾时怎么办？',
      '谁来保证规则被遵守？',
    ],
    aiProject: '做「岛屿生存模拟器」，孩子设定规则看社区能撑多久。',
    bilibiliVideos: [{ title: 'The Island Conundrum', bvid: 'BV1var5YkEvR', url: 'https://www.bilibili.com/video/BV1var5YkEvR/' }],
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Island%20Conundrum',
  },
  {
    id: 'moonshot',
    title: '登月难题',
    original: 'The Moonshot Conundrum',
    category: '科学·探索',
    situation: '一个巨型太空计划要消耗大量资源。',
    question: '该把资源投给登月，还是先解决地球上的问题？',
    discussion: [
      '探索精神 vs 民生改善，钱该花在哪？',
      '今天的投入，算不算给未来的投资？',
    ],
    aiProject: '做「太空计划预算分配」小游戏，在有限预算里做选择。',
    bilibiliVideos: [{ title: '#32 The Moonshot Conundrum', bvid: 'BV1u16JYLEUv', url: 'https://www.bilibili.com/video/BV1u16JYLEUv/' }],
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Moonshot%20Conundrum',
  },
  {
    id: 'nasa',
    title: 'NASA 任务难题',
    original: 'The NASA Conundrum',
    category: '科学·探索',
    situation: '航天机构要在多个任务间排优先级。',
    question: 'NASA 该优先做什么任务？',
    discussion: [
      '科研、载人、商业、教育，目标互相打架时怎么排？',
      '纳税人的钱该怎么花？',
    ],
    aiProject: '做「任务优先级投票」页，孩子投票并看到理由汇总。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20NASA%20Conundrum',
    bilibiliVideos: [{ title: 'The NASA Conundrum', bvid: 'BV1var5YkECP', url: 'https://www.bilibili.com/video/BV1var5YkECP/' }],
  },
  {
    id: 'speed',
    title: '速度难题',
    original: 'The Speed Conundrum',
    category: '逻辑·资源',
    situation: '更快的交通工具不断出现。',
    question: '多快算太快？安全与效率的边界在哪？',
    discussion: [
      '限速是谁的利益？',
      '技术能消除风险吗，还是只是转移了风险？',
    ],
    aiProject: '做「速度与安全」计算器，调速度看事故概率变化。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Speed%20Conundrum',
    bilibiliVideos: [{ title: 'The Speed Conundrum', bvid: 'BV1ver5Y3EFh', url: 'https://www.bilibili.com/video/BV1ver5Y3EFh/' }],
  },
  {
    id: 'masterpiece',
    title: '杰作难题',
    original: 'The Masterpiece Conundrum',
    category: '创意·审美',
    situation: '一幅画被称为杰作，但没人说得清为什么。',
    question: '谁来判断一件作品是杰作？AI 算不算艺术家？',
    discussion: ['原创、评价、AI 艺术，边界在哪？', '价值是谁赋予的？'],
    aiProject: '用 AI 画画，再做「我的杰作画廊」，孩子自己写"为什么这是杰作"。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Masterpiece%20Conundrum',
    bilibiliVideos: [{ title: 'The Masterpiece Conundrum', bvid: 'BV1ver5Y3EVn', url: 'https://www.bilibili.com/video/BV1ver5Y3EVn/' }],
  },
  {
    id: 'blue-comet',
    title: '蓝彗星难题',
    original: 'The Blue Comet Conundrum',
    category: '科学·探索',
    situation: '一颗罕见蓝彗星只能观测很短时间。',
    question: '有限的观测机会怎么分配？',
    discussion: ['科学、公众、商业，谁该优先看到？', '错过这次，要再等上百年，值得吗？'],
    aiProject: '做「彗星观测倒计时」页，附观测指南。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Blue%20Comet%20Conundrum',
    bilibiliVideos: [{ title: 'The Blue Comet Conundrum', bvid: 'BV1VxKt6DEvy', url: 'https://www.bilibili.com/video/BV1VxKt6DEvy/' }],
  },
  {
    id: 'treasure',
    title: '宝藏难题',
    original: 'The Treasure Conundrum',
    category: '逻辑·资源',
    situation: '有人发现了一批宝藏。',
    question: '宝藏归发现者、国家，还是原本的主人？',
    discussion: ['产权、历史、公平，三方冲突怎么解？', '时间过去越久，归属越清楚还是越模糊？'],
    aiProject: '做「寻宝地图」小游戏，埋藏与发现的规则由孩子定。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Treasure%20Conundrum',
    bilibiliVideos: [{ title: 'The Treasure Conundrum', bvid: 'BV1yf6hYNEFj', url: 'https://www.bilibili.com/video/BV1yf6hYNEFj/' }, { title: 'The Treasure Conundrum', bvid: 'BV13XK465EwC', url: 'https://www.bilibili.com/video/BV13XK465EwC/' }],
  },
  {
    id: 'fox',
    title: '狐狸发现难题',
    original: 'The Fox Conundrum',
    category: '伦理·公平',
    situation: '科学家发现了一个狐狸新物种。',
    question: '谁对这次发现最重要——科学家、本地人、政府，还是运气？',
    discussion: ['"贡献"怎么定义？', '团队合作里，谁不可替代？'],
    aiProject: '做「物种发现故事」页，孩子编排不同角色的贡献。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Fox%20Conundrum',
    bilibiliVideos: [{ title: 'The Fox Conundrum', bvid: 'BV17t6hY4EfV', url: 'https://www.bilibili.com/video/BV17t6hY4EfV/' }, { title: 'The Fox Conundrum', bvid: 'BV13B67YGEZD', url: 'https://www.bilibili.com/video/BV13B67YGEZD/' }, { title: 'The Fox Conundrum', bvid: 'BV1DXK46VEhE', url: 'https://www.bilibili.com/video/BV1DXK46VEhE/' }],
  },
  {
    id: 'chocolate',
    title: '巧克力配方难题',
    original: 'The Chocolate Conundrum',
    category: '伦理·公平',
    situation: 'AstraSweets 靠一个秘密配方走红，配方是某人发明的。',
    question: '发明者能不能在自己的配方里用这个秘密原料？',
    discussion: ['知识产权、公平、创新激励，边界在哪？', '没有秘密，还会有创新吗？'],
    aiProject: '做「我的秘密配方」品牌页，孩子设计自己的"秘密"并讲所有权。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Chocolate%20Conundrum',
    bilibiliVideos: [{ title: 'The Chocolate Conundrum', bvid: 'BV1Et6hY4Exn', url: 'https://www.bilibili.com/video/BV1Et6hY4Exn/' }, { title: 'The Chocolate Conundrum', bvid: 'BV1UdK463Emx', url: 'https://www.bilibili.com/video/BV1UdK463Emx/' }],
  },
  {
    id: 'pizza',
    title: '披萨分配难题',
    original: 'The Pizza Conundrum',
    category: '逻辑·资源',
    situation: '一块披萨要分给人数不同、胃口不同的人。',
    question: '怎么分才公平？',
    discussion: ['"公平"是平均分，还是按需分？', '算法能解决公平吗？'],
    aiProject: '做「公平分披萨」计算器，输入人数与偏好出切法。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Pizza%20Conundrum',
    bilibiliVideos: [{ title: 'The Pizza Conundrum', bvid: 'BV1ft6hYxE3n', url: 'https://www.bilibili.com/video/BV1ft6hYxE3n/' }, { title: 'The Pizza Conundrum', bvid: 'BV1YmK462E5U', url: 'https://www.bilibili.com/video/BV1YmK462E5U/' }],
  },
  {
    id: 'martian',
    title: '火星领导难题',
    original: 'The Martian Conundrum',
    category: '科学·探索',
    situation: '首批火星任务选出 5 名宇航员。',
    question: '谁应该当领导？',
    discussion: ['领导力品质有哪些？', '民主选举，还是能力优先？'],
    aiProject: '做「火星任务组队」模拟，孩子选队员并定领导规则。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Martian%20Conundrum',
    bilibiliVideos: [{ title: 'The Martian Conundrum', bvid: 'BV17t6hY4EZA', url: 'https://www.bilibili.com/video/BV17t6hY4EZA/' }, { title: 'The Martian Conundrum', bvid: 'BV1KAKt6qEcg', url: 'https://www.bilibili.com/video/BV1KAKt6qEcg/' }],
  },
  {
    id: 'dinosaur',
    title: '恐龙复活难题',
    original: 'The Dinosaur Conundrum',
    category: '科学·探索',
    situation: '技术可能让灭绝恐龙重生。',
    question: '该不该复活灭绝物种？',
    discussion: ['伦理、生态、科学价值，谁优先？', '复活之后，谁来负责？'],
    aiProject: '做「恐龙图鉴」，孩子给每种恐龙写"该不该复活"的理由。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Dinosaur%20Conundrum',
    bilibiliVideos: [{ title: 'The Dinosaur Conundrum', bvid: 'BV1pMKt6AE18', url: 'https://www.bilibili.com/video/BV1pMKt6AE18/' }, { title: 'The Dinosaur Conundrum', bvid: 'BV1X56EY2Emx', url: 'https://www.bilibili.com/video/BV1X56EY2Emx/' }],
  },
  {
    id: 'flying-bike',
    title: '飞行自行车难题',
    original: 'The Flying Bike Conundrum',
    category: '科学·探索',
    situation: '飞行自行车被发明出来了。',
    question: '该允许满街飞吗？',
    discussion: ['安全、监管、个人自由，怎么平衡？', '新技术的规则，该事先定还是出了事再定？'],
    aiProject: '做「未来交通工具」设计页，孩子画规则并模拟交通。',
    bilibiliVideos: [{ title: 'The Flying Bike Conundrum', bvid: 'BV1CKKt6eEy3', url: 'https://www.bilibili.com/video/BV1CKKt6eEy3/' }],
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Flying%20Bike%20Conundrum',
  },
  {
    id: 'alien',
    title: '外星接触难题',
    original: 'The Alien Conundrum',
    category: '科学·探索',
    situation: '人类可能接触到外星文明。',
    question: '第一句话该说什么？要不要主动联系？',
    discussion: ['风险、沟通、谁代表人类，怎么定？', '沉默更安全，还是更危险？'],
    aiProject: '做「外星问候语」生成器，孩子写并解释自己的选择。',
    bilibiliVideos: [{ title: 'The Alien Conundrum', bvid: 'BV14fK46uEtj', url: 'https://www.bilibili.com/video/BV14fK46uEtj/' }, { title: '#10 The Alien Conundrum', bvid: 'BV1cw6nYeEZ3', url: 'https://www.bilibili.com/video/BV1cw6nYeEZ3/' }, { title: 'The Alien Conundrum', bvid: 'BV1My67YMEdt', url: 'https://www.bilibili.com/video/BV1My67YMEdt/' }],
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Alien%20Conundrum',
  },
  {
    id: 'airport',
    title: '机场难题',
    original: 'The Airport Conundrum',
    category: '逻辑·资源',
    situation: '城市要扩建机场。',
    question: '建在哪、怎么平衡居民与效率？',
    discussion: ['征地、噪声、便利，冲突如何调和？', '受益的人和受损的人，不是同一群人时怎么办？'],
    aiProject: '做「机场选址」模拟，调参数看不同群体反应。',
    bilibiliVideos: [{ title: '#11 The Airport Conundrum', bvid: 'BV1366JYUERX', url: 'https://www.bilibili.com/video/BV1366JYUERX/' }, { title: 'The Airport Conundrum', bvid: 'BV11wKt6TE8r', url: 'https://www.bilibili.com/video/BV11wKt6TE8r/' }],
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Airport%20Conundrum',
  },
  {
    id: 'neighbor',
    title: '邻居冲突难题',
    original: 'The Neighbor Conundrum',
    category: '伦理·公平',
    situation: '两户邻居起了冲突。',
    question: '怎么解决？谁来调解？',
    discussion: ['沟通、规则、共情，哪种方式更管用？', '和解之后，关系怎么修复？'],
    aiProject: '做「邻里公约」生成器，孩子写一条大家都能接受的约定。',
    bilibiliVideos: [{ title: 'The Neighbor Conundrum', bvid: 'BV1HtK46bEqZ', url: 'https://www.bilibili.com/video/BV1HtK46bEqZ/' }, { title: '#12 The Neighbor Conundrum', bvid: 'BV1m1rcYxEGp', url: 'https://www.bilibili.com/video/BV1m1rcYxEGp/' }, { title: 'The Neighbor Conundrum', bvid: 'BV1uy67YMEP4', url: 'https://www.bilibili.com/video/BV1uy67YMEP4/' }],
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Neighbor%20Conundrum',
  },
  {
    id: 'lake',
    title: '湖泊难题',
    original: 'The Lake Conundrum',
    category: '逻辑·资源',
    situation: '一座公共湖泊被过度使用、开始恶化。',
    question: '湖该怎么管？',
    discussion: ['"公有地悲剧"怎么破？', '个人自由与集体责任怎么分？'],
    aiProject: '做「湖泊保护倡议」页，孩子提出并解释自己的管理方案。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Lake%20Conundrum',
    bilibiliVideos: [{ title: 'The Lake Conundrum', bvid: 'BV1Zt6hYxEoA', url: 'https://www.bilibili.com/video/BV1Zt6hYxEoA/' }, { title: 'The Lake Conundrum', bvid: 'BV1EiCgY3Eih', url: 'https://www.bilibili.com/video/BV1EiCgY3Eih/' }, { title: '湖泊难题', bvid: 'BV1YK411Q79T', url: 'https://www.bilibili.com/video/BV1YK411Q79T/' }],
  },
  {
    id: 'lake-returns',
    title: '湖泊回归难题',
    original: 'The Lake Returns Conundrum',
    category: '逻辑·资源',
    situation: '湖泊治理后慢慢恢复，又回到大家手里。',
    question: '恢复后怎么用，才不再重蹈覆辙？',
    discussion: ['短期享受与长期责任，怎么同时守住？', '规则谁来监督？'],
    aiProject: '（接续上一题）做"使用公约"续作，孩子定长期规则。',
    bilibiliVideos: [{ title: 'The Lake Returns Conundrum', bvid: 'BV1m6C3Y4Et9', url: 'https://www.bilibili.com/video/BV1m6C3Y4Et9/' }],
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Lake%20Returns%20Conundrum',
  },
  {
    id: 'halloween',
    title: '万圣节难题',
    original: 'The Halloween Conundrum',
    category: '节日·情境',
    situation: '节日里糖果、安全、热闹要兼顾。',
    question: '糖果怎么分、安全与乐趣怎么平衡？',
    discussion: ['公平、安全、文化习惯，怎么兼顾？', '热闹和安静，谁该让步？'],
    aiProject: '做「万圣节糖果规划」小工具，按人数与过敏算分配。',
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Halloween%20Conundrum',
    bilibiliVideos: [{ title: 'The Halloween Conundrum', bvid: 'BV15Sr3YeEVy', url: 'https://www.bilibili.com/video/BV15Sr3YeEVy/' }],
  },
  {
    id: 'weather',
    title: '天气难题',
    original: 'The Weather Conundrum',
    category: '科学·探索',
    situation: '极端天气越来越频繁。',
    question: '怎么应对、责任在谁？',
    discussion: ['防灾、个人责任、科技作用，怎么分工？', '预警发出后，谁来行动？'],
    aiProject: '做「天气应急清单」生成器，输入场景出准备清单。',
    bilibiliVideos: [{ title: '马斯克网校考题 #16', bvid: 'BV1Yqr5YuELi', url: 'https://www.bilibili.com/video/BV1Yqr5YuELi/' }],
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Weather%20Conundrum',
  },
  {
    id: 'art',
    title: '艺术难题',
    original: 'The Art Conundrum',
    category: '创意·审美',
    situation: '一件作品算不算艺术，争论不休。',
    question: '什么算艺术？AI 生成的作品算吗？',
    discussion: ['定义、价值、原创，边界在哪？', '人人都能做，艺术还珍贵吗？'],
    aiProject: '做「我的数字艺术展」，孩子策展并写策展词。',
    bilibiliVideos: [{ title: '马斯克网校考题 #15', bvid: 'BV1Yqr5YuEUn', url: 'https://www.bilibili.com/video/BV1Yqr5YuEUn/' }],
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Art%20Conundrum',
  },
  {
    id: 'tree',
    title: '大树难题',
    original: 'The Tree Conundrum',
    category: '节日·情境',
    situation: '一棵老树挡在了开发项目前面。',
    question: '砍，还是留？',
    discussion: ['记忆、生态、发展，谁为重？', '一棵树的价值，怎么算？'],
    aiProject: '做「树木故事地图」，孩子给身边的树写"它见证了什么"。',
    bilibiliVideos: [{ title: '马斯克网校考题 #17', bvid: 'BV1Yqr5YuEEL', url: 'https://www.bilibili.com/video/BV1Yqr5YuEEL/' }, { title: 'The Tree Conundrum', bvid: 'BV1uk67YzEew', url: 'https://www.bilibili.com/video/BV1uk67YzEew/' }],
    bilibiliSearch: 'https://search.bilibili.com/all?keyword=Astra%20Nova%20The%20Tree%20Conundrum',
  },
];
